name: pounders

channels:
  - defaults
  - conda-forge

dependencies:
  - python >=3.7
  - pip
  - pytest
  - pytest-cov

  # Package dependencies
  - numpy
  - numba
  - pandas
  - scipy

  # Misc
  - black
  - flake8
  - pdbpp
  - pre-commit
